# Generated by Django 3.2 on 2023-09-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirstackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('query', models.TextField(blank=True, default='', verbose_name='Query')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Variables')),
                ('filters', models.TextField(blank=True, choices=[('NFT_PRIZE_IN_USDC', 'NFT Prize in USDC'), ('', 'None')], default='', verbose_name='Filters')),
                ('limit', models.IntegerField(blank=True, default=1000, verbose_name='Limit Pages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('origin', models.CharField(blank=True, default='', max_length=100, verbose_name='Origin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(blank=True, db_index=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacache.tag')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacache.userdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userdata',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, through='datacache.UserTags', to='datacache.Tag', verbose_name='Tags'),
        ),
    ]
