# Generated by Django 3.2 on 2023-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airstackconfig',
            name='filter_variables',
            field=models.JSONField(blank=True, default=dict, verbose_name='Filter Variables'),
        ),
    ]
