# Generated by Django 3.2 on 2023-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0002_airstackconfig_filter_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='airstackconfig',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
