# Generated by Django 3.2 on 2023-09-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0003_airstackconfig_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airstackconfig',
            name='filter_variables',
        ),
        migrations.RemoveField(
            model_name='airstackconfig',
            name='filters',
        ),
        migrations.AddField(
            model_name='airstackconfig',
            name='expression',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Expression'),
        ),
        migrations.AddField(
            model_name='airstackconfig',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='airstack_config', to='datacache.tag', verbose_name='Tag'),
        ),
    ]
