# Generated by Django 3.2 on 2023-09-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0004_auto_20230923_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airstackconfig',
            name='name',
        ),
    ]
