# Generated by Django 3.2 on 2023-09-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0006_airstackconfig_support_list_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnSyncWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(blank=True, db_index=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
