# Generated by Django 3.2 on 2023-09-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0007_unsyncwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('body', models.CharField(blank=True, default='', max_length=100, verbose_name='Body')),
                ('boardcast', models.BooleanField(default=False, verbose_name='BoardCast')),
                ('receiver', models.TextField(blank=True, default='', verbose_name='Receiver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
