# Generated by Django 3.2 on 2023-09-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacache', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheGraphConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, default='', verbose_name='Description')),
                ('url', models.TextField(blank=True, default='', verbose_name='Url')),
                ('query', models.TextField(blank=True, default='', verbose_name='Query')),
                ('expression', models.CharField(blank=True, default='', max_length=255, verbose_name='Expression')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thegraph_config', to='datacache.tag', verbose_name='Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
